"use client";
import { Activity, AlertTriangle, Bell, BriefcaseBusiness, Calculator, ChevronDown, ChevronRight, CircleDollarSign, Command, Folder, HeartHandshake, LayoutDashboard, Lightbulb, Menu, Plus, Search, Settings, Sparkles, Star, Stethoscope, Target, Trash2, UserRound, Users, Wrench, X } from "lucide-react";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { defaultHubState, HubState, HubTask, loadHubState, saveHubState, TaskLane } from "@/lib/hub-data";

const groups = [
 { label: "Command", items: [["Dashboard", LayoutDashboard], ["Action Center", Target], ["Alerts", AlertTriangle]] },
 { label: "Life areas", items: [["Work", BriefcaseBusiness], ["Personal", UserRound], ["Financial", CircleDollarSign], ["Health", Stethoscope], ["Relationships", HeartHandshake], ["Knowledge", Lightbulb]] }
] as const;
const folderData = [{name:"Projects", children:["Studio refresh","Fall travel"]},{name:"Resources",children:["Reading list"]}];
function IconButton({label,children,onClick,className=""}:{label:string;children:React.ReactNode;onClick?:()=>void;className?:string}) {
 return <button className={"icon-button "+className} aria-label={label} title={label} onClick={onClick}>{children}</button>;
}
export function MasterHub() {
 const [state,setState]=useState<HubState>(defaultHubState), [ready,setReady]=useState(false);
 const [menu,setMenu]=useState(false), [capture,setCapture]=useState(false), [notices,setNotices]=useState(false);
 const [query,setQuery]=useState(""), [active,setActive]=useState("Dashboard"), [expanded,setExpanded]=useState(["Projects"]), [toast,setToast]=useState("");
 const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const id=window.setTimeout(()=>{setState(loadHubState(window.localStorage));setReady(true)},0);return()=>window.clearTimeout(id)},[]);
 useEffect(()=>{if(ready)saveHubState(state,window.localStorage)},[ready,state]);
 useEffect(()=>{const keys=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchRef.current?.focus()}if(e.key==="Escape"){setCapture(false);setNotices(false);setMenu(false)}};window.addEventListener("keydown",keys);return()=>window.removeEventListener("keydown",keys)},[]);
 const tasks=useMemo(()=>state.tasks.filter(t=>t.title.toLowerCase().includes(query.toLowerCase())),[state.tasks,query]);
 const open=state.tasks.filter(t=>!t.complete).length, important=state.tasks.filter(t=>t.important&&!t.complete).length;
 const progress=Math.round(state.tasks.filter(t=>t.complete).length/Math.max(state.tasks.length,1)*100);
 const notify=(s:string)=>{setToast(s);window.setTimeout(()=>setToast(""),2200)};
 const update=(id:string,p:Partial<HubTask>)=>setState(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,...p}:t)}));
 const remove=(id:string)=>{if(window.confirm("Delete this task? This cannot be undone.")){setState(s=>({...s,tasks:s.tasks.filter(t=>t.id!==id)}));notify("Task deleted")}};
 const add=(title:string,lane:TaskLane,star:boolean)=>{setState(s=>({...s,tasks:[{id:crypto.randomUUID(),title,lane,important:star,complete:false,due:"Today"},...s.tasks]}));setCapture(false);notify("Task captured")};
 const choose=(name:string)=>{setActive(name);setMenu(false);notify(name+" selected")};
 return <div className="app-shell">
  <button className={"scrim "+(menu?"visible":"")} aria-label="Close navigation" onClick={()=>setMenu(false)}/>
  <aside className={"sidebar "+(menu?"open":"")}>
   <div className="brand"><span className="brand-mark"><Command size={18}/></span><span>MASTER HUB</span><IconButton label="Close menu" className="mobile-close" onClick={()=>setMenu(false)}><X size={18}/></IconButton></div>
   <nav aria-label="Primary navigation">{groups.map(g=><div className="nav-group" key={g.label}><p>{g.label}</p>{g.items.map(([name,Icon])=><button key={name} className={"nav-item "+(active===name?"active":"")} onClick={()=>choose(name)}><Icon size={17}/><span>{name}</span>{name==="Alerts"&&<em>3</em>}</button>)}</div>)}
    <div className="nav-group folder-group"><p>Library <button aria-label="Add folder"><Plus size={14}/></button></p>{folderData.map(f=><div key={f.name}><button className="nav-item folder" onClick={()=>setExpanded(v=>v.includes(f.name)?v.filter(x=>x!==f.name):[...v,f.name])}>{expanded.includes(f.name)?<ChevronDown size={14}/>:<ChevronRight size={14}/>}<Folder size={16}/><span>{f.name}</span></button>{expanded.includes(f.name)&&f.children.map(c=><button className="folder-child" key={c} onClick={()=>notify(c+" opened")}>{c}</button>)}</div>)}</div>
   </nav>
   <div className="sidebar-footer"><button className="profile"><span className="avatar">SS</span><span><strong>Sam Salem</strong><small>Workspace owner</small></span><Settings size={16}/></button></div>
  </aside>
  <div className="main-wrap">
   <header className="topbar"><IconButton label="Open menu" className="menu-button" onClick={()=>setMenu(true)}><Menu size={20}/></IconButton><div className="search-wrap"><Search size={17}/><input ref={searchRef} type="search" aria-label="Search Master Hub" placeholder="Search tasks, projects, and notes..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>Ctrl K</kbd></div><button className="capture-button" onClick={()=>setCapture(true)}><Plus size={17}/><span>Quick capture</span></button><div className="notice-anchor"><IconButton label="Notifications" onClick={()=>setNotices(v=>!v)}><Bell size={19}/>{state.notifications>0&&<span className="notice-dot"/>}</IconButton>{notices&&<Notifications onClose={()=>{setNotices(false);setState(s=>({...s,notifications:0}))}}/>}</div></header>
   <main>
    <section className="welcome-row"><div><p className="eyebrow">WEDNESDAY · SEPTEMBER 2</p><h1>Good evening, Sam.</h1><p>Here’s the pulse of everything that matters.</p></div><div className="status-chip"><span/>All systems in sync</div></section>
    <section className="metric-grid" aria-label="Overview"><Metric label="Open actions" value={String(open)} note="2 due today" icon={<Target/>} accent="violet"/><Metric label="Important" value={String(important)} note="Needs your focus" icon={<Star/>} accent="amber"/><Metric label="Active projects" value={String(state.projects.length)} note="Across 3 life areas" icon={<BriefcaseBusiness/>} accent="teal"/><Metric label="Weekly progress" value={progress+"%"} note="Keep the momentum" icon={<Activity/>} accent="blue" progress={progress}/></section>
    <section className="content-grid">
     <div className="panel action-panel"><div className="panel-heading"><div><span className="overline">PRIORITY QUEUE</span><h2>Action Center</h2></div><button className="text-button" onClick={()=>setCapture(true)}>Add action <Plus size={15}/></button></div><div className="lane-tabs"><span>All actions</span><small>{tasks.length}</small></div><div className="task-list">{tasks.length?tasks.map(t=><TaskRow key={t.id} task={t} update={p=>update(t.id,p)} remove={()=>remove(t.id)}/>):<div className="empty-state"><Search size={24}/><strong>No actions found</strong><span>Try a broader search or capture a new task.</span></div>}</div><button className="panel-footer" onClick={()=>setQuery("")}>View all actions <ChevronRight size={15}/></button></div>
     <div className="side-stack"><div className="panel focus-card"><span className="overline">TODAY’S FOCUS</span><div className="focus-ring"><div><strong>{open}</strong><span>open</span></div></div><h3>Protect your attention.</h3><p>Complete the highest-leverage work before opening a new loop.</p><div className="focus-legend"><span><i/>Work</span><span><i/>Personal</span></div></div><a className="quote-card" href="https://docs.google.com/spreadsheets/" target="_blank" rel="noreferrer"><span className="quote-icon"><Calculator size={21}/></span><span><small>QUICK TOOL</small><strong>Job Quote Calculator</strong><em>Open calculator <ChevronRight size={14}/></em></span></a></div>
    </section>
    <section className="lower-grid"><div className="panel projects-panel"><div className="panel-heading"><div><span className="overline">IN MOTION</span><h2>Projects</h2></div><button className="text-button" onClick={()=>notify("Projects selected")}>View all <ChevronRight size={14}/></button></div><div className="project-list">{state.projects.map(p=><div className="project-row" key={p.id}><span className="project-monogram" style={{"--accent":p.accent} as React.CSSProperties}>{p.name[0]}</span><div><strong>{p.name}</strong><small>{p.area}</small><div className="progress"><span style={{width:p.progress+"%",background:p.accent}}/></div></div><b>{p.progress}%</b></div>)}</div></div><div className="panel tools-panel"><div className="panel-heading"><div><span className="overline">SHORTCUTS</span><h2>Tools</h2></div></div><div className="tool-grid"><Tool icon={<Calculator/>} name="Quote calculator" onClick={()=>window.open("https://docs.google.com/spreadsheets/","_blank")}/><Tool icon={<Sparkles/>} name="Idea distiller" onClick={()=>notify("Idea distiller ready")}/><Tool icon={<Wrench/>} name="Admin console" onClick={()=>choose("Admin")}/><Tool icon={<Users/>} name="Contacts" onClick={()=>choose("Relationships")}/></div></div></section>
   </main>
  </div>
  {capture&&<Capture onClose={()=>setCapture(false)} onAdd={add}/>}
  {toast&&<div className="toast" role="status">{toast}</div>}
 </div>;
}
function Metric({label,value,note,icon,accent,progress}:{label:string;value:string;note:string;icon:React.ReactNode;accent:string;progress?:number}){return <article className={"metric-card "+accent}><div className="metric-top"><span className="metric-icon">{icon}</span><span>↗</span></div><strong>{value}</strong><h3>{label}</h3>{progress!==undefined&&<div className="mini-progress"><span style={{width:progress+"%"}}/></div>}<p>{note}</p></article>}
function TaskRow({task,update,remove}:{task:HubTask;update:(p:Partial<HubTask>)=>void;remove:()=>void}){const [editing,setEditing]=useState(false),[title,setTitle]=useState(task.title);const save=()=>{if(title.trim()){update({title:title.trim()});setEditing(false)}};return <div className={"task-row "+(task.complete?"complete":"")}><button className="check" aria-label={task.complete?"Mark "+task.title+" incomplete":"Complete "+task.title} onClick={()=>update({complete:!task.complete})}>{task.complete?"✓":""}</button><span className={"lane "+task.lane.toLowerCase()}>{task.lane}</span><div className="task-copy">{editing?<input aria-label="Edit task title" autoFocus value={title} onChange={e=>setTitle(e.target.value)} onBlur={save} onKeyDown={e=>{if(e.key==="Enter")save();if(e.key==="Escape"){setTitle(task.title);setEditing(false)}}}/>:<button className="task-title" onClick={()=>setEditing(true)}>{task.title}</button>}<small>{task.due??"No due date"}</small></div><IconButton label={(task.important?"Remove importance from ":"Mark important ")+task.title} className={task.important?"starred":""} onClick={()=>update({important:!task.important})}><Star size={17} fill={task.important?"currentColor":"none"}/></IconButton><IconButton label={"Delete "+task.title} className="delete-button" onClick={remove}><Trash2 size={16}/></IconButton></div>}
function Capture({onClose,onAdd}:{onClose:()=>void;onAdd:(t:string,l:TaskLane,i:boolean)=>void}){const [title,setTitle]=useState(""),[lane,setLane]=useState<TaskLane>("D"),[star,setStar]=useState(false),[error,setError]=useState("");const submit=(e:FormEvent)=>{e.preventDefault();if(title.trim().length<3){setError("Add at least 3 characters so the action is clear.");return}onAdd(title.trim(),lane,star)};return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="capture-title"><div className="modal-heading"><div><span className="overline">NEW ACTION</span><h2 id="capture-title">Quick capture</h2></div><IconButton label="Close quick capture" onClick={onClose}><X size={19}/></IconButton></div><form onSubmit={submit} noValidate><label htmlFor="task-title">What needs your attention?</label><input id="task-title" autoFocus placeholder="e.g. Review the vendor proposal" value={title} onChange={e=>{setTitle(e.target.value);setError("")}} aria-invalid={!!error} aria-describedby={error?"title-error":undefined}/>{error&&<p id="title-error" className="form-error">{error}</p>}<fieldset><legend>Area</legend><label><input type="radio" name="lane" checked={lane==="D"} onChange={()=>setLane("D")}/><span>D</span>Work</label><label><input type="radio" name="lane" checked={lane==="P"} onChange={()=>setLane("P")}/><span>P</span>Personal</label></fieldset><label className="important-check"><input type="checkbox" checked={star} onChange={e=>setStar(e.target.checked)}/><Star size={16}/>Mark as important</label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button">Capture action</button></div></form></section></div>}
function Notifications({onClose}:{onClose:()=>void}){return <div className="notification-panel"><div><strong>Notifications</strong><button onClick={onClose}>Mark all read</button></div>{[["Proposal due today","James is waiting on the revised scope."],["Weekly review ready","Your latest summary is available."],["2 important actions","Keep your focus list intentional."]].map((n,i)=><article key={n[0]}><span className={"notification-icon n"+i}><Bell size={14}/></span><p><strong>{n[0]}</strong><small>{n[1]}</small></p></article>)}</div>}
function Tool({icon,name,onClick}:{icon:React.ReactNode;name:string;onClick:()=>void}){return <button className="tool-button" onClick={onClick}><span>{icon}</span><strong>{name}</strong><ChevronRight size={14}/></button>}